package cn.edu.xmu.goods.mapper;

import cn.edu.xmu.goods.model.po.GoodFlashSaleItemPo;
import cn.edu.xmu.goods.model.po.GoodFlashSaleItemPoExample;
import java.util.List;

public interface GoodFlashSaleItemPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale_item
     *
     * @mbg.generated
     */
    int insert(GoodFlashSaleItemPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale_item
     *
     * @mbg.generated
     */
    int insertSelective(GoodFlashSaleItemPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale_item
     *
     * @mbg.generated
     */
    List<GoodFlashSaleItemPo> selectByExample(GoodFlashSaleItemPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale_item
     *
     * @mbg.generated
     */
    GoodFlashSaleItemPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodFlashSaleItemPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodFlashSaleItemPo record);
}