package cn.edu.xmu.goods.mapper;

import cn.edu.xmu.goods.model.po.GoodFlashSalePo;
import cn.edu.xmu.goods.model.po.GoodFlashSalePoExample;
import java.util.List;

public interface GoodFlashSalePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale
     *
     * @mbg.generated
     */
    int insert(GoodFlashSalePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale
     *
     * @mbg.generated
     */
    int insertSelective(GoodFlashSalePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale
     *
     * @mbg.generated
     */
    List<GoodFlashSalePo> selectByExample(GoodFlashSalePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale
     *
     * @mbg.generated
     */
    GoodFlashSalePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodFlashSalePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodFlashSalePo record);
}