management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8083
  tomcat:
    threads:
      max: 1000

spring:
  application:
    name: ininterface
  profiles:
    active: dev


mybatis:
  #po对象的包
  type-aliases-package: cn.edu.xmu.goods.model
  #mapper.xml所在的位置
  mapper-locations: classpath*:cn.edu.xmu.goods.mapper/*.xml
  #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
  configuration:
    #输出产生的SQL
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

goodsservice:
  #是否对数据库中的未初始化的数据初始化
  initialization: true
  #分布式锁失效时间（秒）
  lockerExpireTime: 30
  #图片存储位置
  imglocation: ./img
  user:
    # user的权限字在Redis中失效秒数
    expiretime: 600
  role:
    # role的权限字在Redis中失效秒数
    expiretime: 600
  login:
    #是否允许重复登录
    multiply: false
    #jwt过期的时间(秒)
    jwtExpire: 3600


#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql

cloud:
  nacos:
    discovery:
      server-addr: 127.0.0.1:8848


dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.example.demo.server
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: 18889
  registry:
    address: nacos://localhost:8848